# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa63941a9e7072fd03fd61a365b1a7f81d23d4a1c6c1a8e711b7657b9f4adeb8f93a34803c504ffbc6eb5cf13ccdd0b1e99a6300b1ec60f7abc4e6649356102

test:
  secret_key_base: 454af58331780e45dfa505d09e634c706bac9921be7f79973505d54de725d5b2fd2544628b4349a34ae9188df4db5557023f7af39251bc33736c0980b8d106d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
